# Build stage
FROM node:20-alpine AS build

WORKDIR /app

RUN mkdir client
COPY client/package*.json ./client

RUN cd client && npm install

COPY common ./common
COPY client ./client

RUN cd client && npm run build

FROM nginx:alpine

COPY --from=build /app/client/dist /usr/share/nginx/html

COPY client/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]