
FROM node:latest

WORKDIR /app

RUN mkdir server
COPY server/package*.json ./server

RUN cd server && npm install

COPY common ./common
COPY server ./server

RUN cd server && npm run build
RUN cd server && npx prisma generate

EXPOSE 4000

WORKDIR /app/server
CMD ["node", "dist/server/src/index.js"]